defaultPortal: viniciusleite
portals:
  - name: viniciusleite
    portalId: 5338832
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CITcy8HiMBIRAA0AAAAA4A0AQAIAAEAAADgY0O3FAiDG-eoUKO7pDDIUot6GNW8H_Q5uuuwsOR7ryq29Gqk6NwAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAAAABEAGAAAAAAAAAIAAAAAAAADPxCFLlZQodSTpBYJ4p-oII2BEGWuhjZSgNuYTFSAFoA
        expiresAt: '2023-02-06T19:27:51.813Z'
    personalAccessKey: >-
      CiQ0MDcxN2FiNC1jYmE0LTQ0MTQtYWIzNS1kZDBhNDM4NDYyYTIQ0O3FAhjG-eoUKhkABeaRgsmyj3LiEpA1DAoDGDzvlttw_IyRSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
